# Generated by Django 2.1.1 on 2019-01-09 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0003_auto_20190109_1510'),
        ('product_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='имя продукта')),
                ('short_desc', models.CharField(blank=True, max_length=60, verbose_name='краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('special_offer', models.CharField(blank=True, max_length=50, null=True, verbose_name='специальное предложение')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='склад')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.Image')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_list.Product_Category')),
            ],
        ),
    ]
