# Generated by Django 2.1.1 on 2019-01-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('special_offer', models.CharField(blank=True, max_length=250, null=True)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
