# Generated by Django 2.1.1 on 2019-01-07 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_list', '0002_auto_20190107_1951'),
        ('product_detail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product_list.Product_Category'),
            preserve_default=False,
        ),
    ]
