# Generated by Django 2.1.1 on 2019-01-09 13:25

import json
from django.db import migrations

from product_detail.models import Product
from product_list.models import Product_Category
from images.models import Image


def populate_data_base_with_products(apps, schema_editor):

    context = {}

    with open('data/context.json') as file:
        context = json.load(file)

    products = []

    products = context["products"]


    for data in products:
        category = Product_Category.objects.get(name=data["product_category"])
        image = Image.objects.get(name=data["image"])
        prod = Product(
            product_category=category,
            name=data["name"],
            image=image,
            short_desc=data["short_desc"],
            description=data["description"],
            special_offer=data["special_offer"],
            price=data["price"],
            quantity=data["quantity"]
            )
        prod.save()


class Migration(migrations.Migration):

    dependencies = [
        ('product_detail', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            populate_data_base_with_products,
            lambda x, y: (x, y)
        )
    ]
