# Generated by Django 2.1.1 on 2019-01-09 13:19

import json

from django.db import migrations

from product_list.models import Product_Category


def populate_data_base_with_categories(apps, schema_editor):

    context = {}

    with open('data/context.json') as file:
        context = json.load(file)

    categories = []

    categories = context["categories"]


    for data in categories:
        category = Product_Category(name=data["name"], description=data["description"], href=data["href"])
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('product_list', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            populate_data_base_with_categories,
            lambda x, y: (x, y)
        )
    ]
