# Generated by Django 2.1.1 on 2019-01-07 17:06

from django.db import migrations


def create_default_product_category(apps, schema_editor):
    Product_Category = apps.get_model('product_list', 'Product_Category')
    Product_Category.objects.create(
        name = 'default category',
        description = 'this is default category'
    )
    

class Migration(migrations.Migration):

    dependencies = [
        ('product_list', '0002_auto_20190107_1951'),
    ]

    operations = [
        migrations.RunPython(
            create_default_product_category,
            lambda x, y: (x, y)
        )
    ]
