# Generated by Django 2.1.1 on 2019-01-11 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_list', '0002_auto_20190109_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_category',
            name='href',
        ),
    ]
