# Generated by Django 2.1.1 on 2019-01-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_list', '0003_auto_20190107_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='href',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
