# Generated by Django 2.1.1 on 2019-01-09 12:10

import json
from django.db import migrations

from images.models import Image


def populate_data_base_with_images(apps, schema_editor):

    context = {}

    with open('data/context.json') as file:
        context = json.load(file)

    products = []

    products = context["products"]


    for data in products:
        image = Image(name=data["image"], value=data["image"])
        image.save()


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20190108_2019'),
    ]

    operations = [
        migrations.RunPython(
            populate_data_base_with_images,
            lambda x, y: (x, y)
        )
    ]
